---
title: "R Notebook"
output: html_notebook
---

# Environmental dataset 

# ---------------------------
# NFI_SST_in_situ_temperature
# ---------------------------

```{r}
library(dplyr)
library(ggplot2)
library(lubridate)
library(plyr)
library(lattice)
library(openair)
```


```{r}
temps <- read.csv("in_situ_temps.csv") # previously been averaged 3-hourly

SST <- read.csv("SST_norfolk_island.csv")
```

# SST plotting

```{r}
SST_1year <- SST %>% filter(between(YYYY,2020,2021))
SST_1year$date <- paste(SST_1year$DD,"/",SST_1year$MM) 
SST_1year$date <- paste(SST_1year$date,"/", SST_1year$YYYY)
SST_1year$date <- as.Date(SST_1year$date, format = "%d / %m / %Y" ) 

SST_filter <- SST_1year %>% 
  filter(date >= as.Date("2020-12-01") & date < as.Date("2021-03-31")) %>%
  select(date, SST_MAX)

p1 <- ggplot(SST_filter, aes(date, SST_MAX))+
  geom_line() +
  scale_x_date(name = "Date", date_breaks = "1 month", date_minor= "1 week") +
  scale_y_continuous(name = "SST Max", limits = c(20,27), breaks = c(20,21,22,23,24,25,26,27))+
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

p1

```

# in situ plotting 

```{r}
# Parse date column 

str(temps)

# Parse time column
temps$date <- ymd_hms(temps$date)

colour <- c("deepskyblue3","darkorchid4","brown")
p2 <- ggplot(temps, aes(date, Temp, group = Site, colour = Site))+
  geom_line() +
  scale_x_datetime(name = "Date", date_breaks = "1 week", date_minor= "1 week") +
  scale_y_continuous(name = "Temperature (C)", limits = c(20,27), breaks = c(20,21,22,23,24,25,26,27))+
  scale_color_manual(values = colour) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

p2

```

# in situ summary statistics 

```{r}
temps

temp <- select(temps, date,Site,Temp)
# Calculate daily median, minimum, maximum speed, SD 

# Median
temp_median <- timeAverage(temp, 
                      avg.time = "day",
                      statistic = "median",
                      type = "Site")

daily_temp_median <- temp_median %>% group_by(Site) %>%
  summarise(mean_median = mean(Temp))

# Max
temp_max <- timeAverage(temp, 
                      avg.time = "day",
                      statistic = "max",
                      type = "Site")

daily_temp_max <- temp_max %>% group_by(Site) %>%
  summarise(mean_median = mean(Temp))


# Min
temp_min <- timeAverage(temp, 
                      avg.time = "day",
                      statistic = "min",
                      type = "Site")

daily_temp_min <- temp_min %>% group_by(Site) %>%
  summarise(mean_median = mean(Temp))

# SD
temp_sd <- timeAverage(temp, 
                      avg.time = "day",
                      statistic = "sd",
                      type = "Site")

daily_temp_sd <- temp_sd %>% group_by(Site) %>%
  summarise(mean_median = mean(Temp))

```


